version: '1.0'
stages:
  - checkout
  - prepare   
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'VaishnaviV1105/cicdrepo'
    revision: main
    git: github      
  SetupAuth:
    image: alpine:3.9
    title: Setting up aws cloud auth
    stage: prepare
    commands:
      - export access_key=$ACCESS_KEY
      -export secret_key=$SECRET_KEY
  DeployWithTerraform:
    image: hashicorp/terraform:0.12.0
    title: Deploying Terraform plan
    stage: deploy
    commands:
      - terraform init
      - terraform apply -auto-approve
